version: '2'
services:
    rainman-app:
        image: rainman
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rainman-mysql:3306/rainman?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rainman-mysql:
        extends:
            file: mysql.yml
            service: rainman-mysql
